# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SHIELD' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SHIELD
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Messaging'
pod 'Firebase/Core'
pod 'Eureka', '~> 5.0'

  target 'SHIELDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SHIELDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
